"""empty message

Revision ID: 0264f65d08fa
Revises: f49553f399f3
Create Date: 2020-09-15 16:02:41.040552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0264f65d08fa'
down_revision = 'f49553f399f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celestial_bodies', sa.Column('background_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('celestial_bodies', 'background_image')
    # ### end Alembic commands ###
